# c-a as my leader
unbind c-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Unbind the defaults
unbind '"'
unbind %

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# don't rename windows automatically
set-option -g allow-rename off

# Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'

set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'duo'
set -g @tmux2k-icons-only true

run '~/.tmux/plugins/tpm/tpm'
