# c-a as my leader
unbind c-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Pane management
bind | split-window -h
bind - split-window -v

# Unbind the defaults
unbind '"'
unbind %

# Switching panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# don't rename windows automatically
set-option -g allow-rename off

# Quick reload
bind r source-file ~/.tmux.conf

# Plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'duo'
set -g @tmux2k-icons-only true

run '~/.tmux/plugins/tpm/tpm'
