vim.keymap.set('i', 'jk', '<Esc>', { desc = "Exit insert mode" })
vim.keymap.set('n', '<leader>S', ':%s//g<Left><Left>', { desc = "Replace command" })
vim.keymap.set('n', '<leader>wv', '<C-w>v<CR>', { desc = "Split window horizontal" })
vim.keymap.set('n', '<leader>ws', '<C-w>s<CR>}', { desc = "Split window vertical" })
vim.keymap.set('n', '<leader>wh', ':exe "vertical resize -" .5<CR>', { desc = "Decrease split vertical size by 5" })
vim.keymap.set('n', '<leader>wl', ':exe "vertical resize +" .5<CR>', { desc = "Increase split vertical size by 5" })
vim.keymap.set('n', '<leader>wj', ':exe "resize -" .5<CR>', { desc = "Decrease split horizontal size by 5" })
vim.keymap.set('n', '<leader>wk', ':exe "resize +" .5<CR>', { desc = "Increase split horizontal size by 5" })
vim.keymap.set('n', '<leader>wr', '<C-w>=<CR>', { desc = "Restore split size" })
vim.keymap.set('n', '<a-}>', '<cmd>bnext<CR>', { desc = "Go to next buffer" })
vim.keymap.set('n', '<a-{>', '<cmd>bprev<CR>', { desc = "Go to previous buffer" })
vim.keymap.set('n', '<a-x>', '<cmd>bdelete<CR>', { desc = "Close buffer" })
vim.keymap.set('n', '<leader>tn', '<cmd>tabnew<CR>', { desc = "Create new tab" })
vim.keymap.set('n', '<leader>tx', '<cmd>tabclose<CR>', { desc = "Close tab" })
vim.keymap.set('n', '<F8>', ':setlocal spell!<CR>', { desc = "Toggle spell check" })
