local keymap = require "je12emy.utils.map"

keymap.imap('jk', '<Esc>', { desc = "Exit insert mode" })
keymap.nmap('<Space>S', ':%s//g<Left><Left>', { desc = "Replace command" })
keymap.nmap('<Space>wv', '<C-w>v<CR>', { desc = "Split window horizontal" })
keymap.nmap('<Space>ws', '<C-w>s<CR>}', { desc = "Split window vertical" })
keymap.nmap('<Space>wh', ':exe "vertical resize -" .5<CR>', { desc = "Decrease split vertical size by 5" })
keymap.nmap('<Space>wl', ':exe "vertical resize +" .5<CR>', { desc = "Increase split vertical size by 5" })
keymap.nmap('<Space>wj', ':exe "resize -" .5<CR>', { desc = "Decrease split horizontal size by 5" })
keymap.nmap('<Space>wk', ':exe "resize +" .5<CR>', { desc = "Increase split horizontal size by 5" })
keymap.nmap('<Space>wr', '<C-w>=<CR>', { desc = "Restore split size" })
keymap.nmap('<a-}>', '<cmd>bnext<CR>', { desc = "Go to next buffer" })
keymap.nmap('<a-{>', '<cmd>bprev<CR>', { desc = "Go to previous buffer" })
keymap.nmap('<a-x>', '<cmd>bdelete<CR>', { desc = "Close buffer" })
keymap.nmap('<Space>tn', '<cmd>tabnew<CR>', { desc = "Create new tab" })
keymap.nmap('<Space>tx', '<cmd>tabclose<CR>', { desc = "Close tab" })
keymap.nmap('<F8>', ':setlocal spell!<CR>', { desc = "Toggle spell check" })
