#! /bin/bash

files="$(find "$HOME" -maxdepth 4 -iname "*.pdf")"

choice=$(printf '%s\n' "${files[@]}" \
        | cut -d '/' -f4- \
        | sed -e 's/Documents/Dcs/g' \
            -e 's/Downloads/Dwn/g' \
            -e 's/Pictures/Pic/g' \
            -e 's/Images/Img/g' \
            -e 's/.pdf//g' \
        | sort -g \
        | tofi --horizontal=true --prompt-text="File: ") || exit 1

if [ "$choice" ]; then
    file=$(
            printf '%s' "$choice" \
                | sed -e 's/Dcs/Documents/g' \
                    -e 's/Dwn/Downloads/g' \
                    -e 's/Pic/Pictures/g' \
                    -e 's/Img/Images/g'
        )
        "zathura" "$HOME/${file}.pdf"
    else
        echo "Program Terminated." && exit 0
fi
